### PR TITLE
add dynamic dns support with dhcp for apiserver vip

### PR DESCRIPTION
**Pull request by jzhoucliqr**
When dynamic DNS is available, the input ‘address’ can be a fqdn without binding to a IP, then kube-vip will use dhclient to get an IP for the hostname of fqdn, then ipUpdater will kick in.

### CODE REVIEW

**Comment by thebsdbox** [comment]
This looks good to me!

Two things though:
1. Can we move the destination merge from `master` to `0.2.1`
2. It could do with some documentation? I've merged the `/docs` (from kube-vip.io) into the `0.2.1` branch so feel free to make a branch from there and add in a few lines of usage 👍

**Review by thebsdbox — APPROVED** [review]
I'm not 100% sure how to test this, but the code changes look good to me.

**Comment by thebsdbox** [comment]
Ah, you may need to rebase... I can't imagine the merge conflicts are too bad :-)

**Comment by jzhoucliqr** [comment]
Rebase done. will add more docs in a separate PR. Curious to know, for the doc, do you use some tools to generate the static website from markdown? I'm also looking for something like this.

**Comment by thebsdbox** [comment]
https://github.com/mixu/markdown-styles 

Then
`generate-md --layout github --input . --output /var/www/kube-vip/`

**Comment by jzhoucliqr** [comment]
Thanks a lot!

**Pull request merged**
